# Cyber-SOC Auto-Responder Main Settings

application:
  name: "Cyber-SOC Auto-Responder"
  version: "1.0.0"
  environment: "development"  # development, staging, production

# Alert Processing Configuration
alerts:
  poll_interval_seconds: 60
  max_concurrent_processing: 10
  batch_size: 50
  retry_attempts: 3
  retry_delay_seconds: 5

# Severity Scoring Thresholds
scoring:
  critical_threshold: 8.5
  high_threshold: 7.0
  medium_threshold: 5.0
  low_threshold: 2.0
  
  # DBIR pattern weights
  dbir_weights:
    malware: 1.5
    social_engineering: 1.3
    privilege_abuse: 1.2
    physical_theft: 1.1
    error: 0.8
    
# Automated Response Thresholds
automation:
  auto_isolate_threshold: 8.0
  auto_scan_threshold: 6.0
  auto_ticket_creation_threshold: 5.0
  require_approval_threshold: 9.0

# File Analysis Settings
file_analysis:
  max_file_size_mb: 100
  supported_extensions: [".exe", ".dll", ".pdf", ".doc", ".docx", ".zip", ".rar"]
  quarantine_path: "./quarantine/"
  
# Integration Timeouts
timeouts:
  splunk_search_timeout: 300
  crowdstrike_api_timeout: 60
  thehive_api_timeout: 45
  yara_scan_timeout: 120

# Rate Limiting
rate_limits:
  splunk_requests_per_minute: 60
  crowdstrike_requests_per_minute: 100
  thehive_requests_per_minute: 30

# Agent Configuration
agents:
  triage:
    model: "gpt-4-turbo-preview"
    temperature: 0.1
    max_tokens: 2000
    
  scanner:
    model: "gpt-4-turbo-preview"
    temperature: 0.0
    max_tokens: 1500
    
  response:
    model: "gpt-4-turbo-preview"
    temperature: 0.0
    max_tokens: 1000
    
  case:
    model: "gpt-4-turbo-preview"
    temperature: 0.2
    max_tokens: 2500

# Monitoring and Alerting
monitoring:
  health_check_interval: 300
  metrics_collection_interval: 60
  alert_on_failed_processing: true
  alert_on_high_error_rate: true
  
# Data Retention
retention:
  alert_data_days: 90
  log_files_days: 30
  quarantine_files_days: 180
  case_data_days: 365 